### PR TITLE
Combine Belgium multiple platform source files (resolves #15) 

### LINKED ISSUE #15: Combine multiple platform source files
Some flags have several source files labelled flag_Linux.* and flag_Windows.*, combine them and get the single file to compile on both (or preferably more) systems

### PR DESCRIPTION
**Pull request by nilsding**
Yes yes

resolves #15

### CODE REVIEW

**Comment by coderobe** [comment]
Testing required for Win32 and Linux x86_64
Tested on Darwin ✔️

**Comment by nilsding** [comment]
Win32 works with MSVC 6 on Win 2k

Fuck Linux

**Comment by nilsding** [comment]
Works fine with clang++ on FreeBSD 11.0

**Comment by seatsea** [comment]
Compiles and runs on Linux

**Pull request merged**
